cmake_minimum_required(VERSION 4.0)
project(CLI)

set(CMAKE_CXX_STANDARD 17)

add_executable(CLI main.cpp
        Engine/InterpreterEngine.cpp
        Engine/InterpreterEngine.h
        Reader/Reader.cpp
        Reader/Reader.h
        Commands/Command.cpp
        Commands/Command.h
        Parser/Parser.cpp
        Parser/Parser.h
        Reader/ConsoleReader.cpp
        Reader/ConsoleReader.h
        Lexer/Lexer.cpp
        Lexer/Lexer.h
        Lexer/Token.cpp
        Lexer/Token.h
        Commands/Echo.cpp
        Commands/Echo.h
        Commands/SimpleCommand.cpp
        Commands/SimpleCommand.h
        CommandDB/CommandDB.cpp
        CommandDB/CommandDB.h
        Commands/Date.cpp
        Commands/Date.h
        Commands/Time.cpp
        Commands/Time.h
        Commands/SingleFileCommand.cpp
        Commands/SingleFileCommand.h
        Commands/Touch.cpp
        Commands/Touch.h
        Commands/TextCommand.cpp
        Commands/TextCommand.h
        Reader/FileReader.cpp
        Reader/FileReader.h
        Commands/Wc.cpp
        Commands/Wc.h
        Commands/Prompt.cpp
        Commands/Prompt.h
        Commands/SingleArgumentCommand.cpp
        Commands/SingleArgumentCommand.h
        Commands/Truncate.cpp
        Commands/Truncate.h
        Commands/Rm.cpp
        Commands/Rm.h
        Commands/Pipe.cpp
        Commands/Pipe.h
        Commands/Tr.cpp
        Commands/Tr.h
        Commands/Batch.cpp
        Commands/Batch.h
        Commands/Head.cpp
        Commands/Head.h
        Reader/StreamReader.cpp
        Reader/StreamReader.h
        Engine/Context.cpp
        Engine/Context.h
        CustomExceptions/SyntaxError.cpp
        CustomExceptions/SyntaxError.h)
